# Generated by Django 4.2.5 on 2023-09-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('atk', models.IntegerField()),
                ('critdmg', models.FloatField()),
                ('critrate', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
